version: '2'
services:
  mysql:
    container_name: pl_test_db
    ports:
      - "33060:3306"
    image: "mysql:5.6.36"
    volumes:
      - ./docker/app.cnf:/etc/mysql/conf.d/app.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
